---
# tasks file for logstash-packages

- name: Stop the Logstash service.
  service: name=logstash state=stopped
  ignore_errors: true

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'
